# Generated by Django 3.1.6 on 2021-02-14 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('args', models.TextField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField()),
                ('excinfo', models.TextField(blank=True, default=None, null=True)),
                ('funcname', models.CharField(max_length=128)),
                ('level', models.PositiveIntegerField()),
                ('lineno', models.PositiveIntegerField()),
                ('message', models.TextField(blank=True, default=None, null=True)),
                ('msg', models.TextField()),
                ('name', models.CharField(max_length=128)),
                ('pathname', models.CharField(max_length=1024)),
                ('process', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('processname', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('sinfo', models.TextField(blank=True, default=None, null=True)),
                ('thread', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('threadname', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('raw', models.TextField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lumber.app')),
            ],
            options={
                'verbose_name_plural': 'Records',
            },
        ),
    ]
